package com.hbm.inventory.recipes.machine.rbmk;

import com.hbm.items.machine.ItemRBMKRod;
import com.hbm.items.machine.rbmk.RBMKRods;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;

/**
 * Spent-fuel-rod-to-pellet recycling, ported from CE's {@code com.hbm.inventory.recipes.RBMKFuelRecipes}
 * (78 lines, read in full).
 * <p>
 * <b>Design note - not a vanilla-style data-driven recipe</b>: CE's real table
 * ({@code LinkedHashMap<ItemStack, ItemStack> recipes}) is keyed on exact-NBT-matched example
 * stacks generated by {@code addRod} (5 enrichment buckets x 2 xenon states, per rod type) - it exists
 * to enumerate example rows for JEI display, not as the live conversion path. The live conversion
 * ({@code makeRBMKPellet(ItemStack)}) is a pure function of the *actual* rod stack's current
 * enrichment/poison state, generically, for any {@link ItemRBMKRod} - that generic function is what
 * this port needs (a recycling machine calls it on whatever specific, player-mutated stack it's
 * holding; a static ingredient/output pair keyed on exact NBT would never match a live stack after
 * even one tick of burn). Per this task's own instruction to use judgment rather than block on a
 * recipe-system redesign, this is kept as plain static logic - not registered as an
 * {@code HbmSimpleRecipe}/vanilla {@code RecipeType} - documented here rather than silently deviating.
 */
public final class RBMKFuelRecipes {

    private RBMKFuelRecipes() {
    }

    /**
     * @return the recycling output for a live rod stack (8x the discretized-stage pellet, CE:
     * {@code makeRBMKPellet}'s fixed count of 8), or {@link ItemStack#EMPTY} if {@code rodStack}
     * isn't an {@link ItemRBMKRod} or its pellet isn't registered.
     */
    public static ItemStack getRecyclingOutput(ItemStack rodStack) {
        if (!(rodStack.getItem() instanceof ItemRBMKRod rod)) return ItemStack.EMPTY;

        // rod.pellet (the real ItemRBMKRod's own object-reference field) is never set by this port's
        // registry (see RBMKRods' own javadoc on why) - resolved by registry name instead.
        ResourceLocation rodId = BuiltInRegistries.ITEM.getKey(rod);
        String pelletId = RBMKRods.getPelletId(rodId.getPath());
        if (pelletId == null) return ItemStack.EMPTY;

        Item pellet = BuiltInRegistries.ITEM.get(ResourceLocation.fromNamespaceAndPath("hbm", pelletId));
        if (pellet == null || pellet == Items.AIR) return ItemStack.EMPTY;

        return new ItemStack(pellet, 8);
    }

    /**
     * The 0-9 pellet "stage" a rod's live state maps onto - CE:
     * {@code RBMKFuelRecipes.makeRBMKPellet}'s damage-value math, ported onto
     * {@code ItemRBMKPellet}'s data-component stage (see
     * {@code com.hbm.items.machine.ItemRBMKPellet#setStage}). 0-4 = depletion bucket (0 = freshest),
     * +5 if xenon poison is at/above 50%.
     */
    public static int computeStage(ItemStack rodStack) {
        double enrichment = ItemRBMKRod.getEnrichment(rodStack);
        double poisonLevel = ItemRBMKRod.getPoisonLevel(rodStack);

        int bucket = 4 - Mth.clamp((int) Math.ceil(enrichment * 5 - 1), 0, 4);
        return bucket + (poisonLevel >= 0.5D ? 5 : 0);
    }
}
