modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

displayURL="https://github.com/Warfactory-Official/Hbm-s-Nuclear-Tech-CE"
issueTrackerURL="https://github.com/Warfactory-Official/Hbm-s-Nuclear-Tech-CE/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile="logo.png"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
