package com.hbm.items;

import com.hbm.creativetabs.CreativeTabContents;
import com.hbm.creativetabs.ModCreativeTabs;
import com.hbm.items.special.ItemFuel;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.neoforged.neoforge.registries.DeferredItem;

/**
 * Hardcoded {@code plate_}/{@code crystal_}/{@code gem_}/{@code waste_}/{@code fragment_} resource
 * items ported from CE's {@code ModItems.java} (docs/phase1/moditems_generative.md section 3). CE
 * hand-wrote each of these as its own field rather than generating them from
 * {@code Mats}/{@code MaterialShapes} - the material sets between the ingot/nugget/billet/powder/
 * plate/crystal families are mismatched enough (see the research report) that a generation loop
 * would either miss items CE has or invent items CE does not, so this file mirrors CE's own
 * approach: one explicit registration per field, with a thin {@link #register(String)}/
 * {@link #registerParts(String)} helper only to remove the {@code new Item(new Item.Properties())}
 * boilerplate for the plain majority.
 *
 * <p>Deliberately excluded from this file, left to other Phase 1 areas:
 * <ul>
 *     <li>{@code plate_cast}/{@code plate_welded} - {@code ItemAutogen}-backed
 *     (moditems_generative.md section 1), already generated by {@link MaterialItemGenerator}.</li>
 *     <li>{@code plate_fuel_u233}/{@code u235}/{@code mox}/{@code pu239}/{@code sa326}/
 *     {@code ra226be}/{@code pu238be} (7 fields) - CE backs these with
 *     {@code ItemPlateFuel extends ItemFuelRod}, a stateful research-reactor fuel item
 *     (durability-encoded "life" counter, reactivity math) with zero relation to the plain
 *     {@code plate_} resource family beyond sharing a name prefix.
 *     {@code com.hbm.items.machine.ItemFuelRod}/{@code ItemPlateFuel} are explicitly claimed by the
 *     items_machine Phase 1 area (docs/phase1/items_machine.md, "port now" table, lines 44/55);
 *     registering {@code plate_fuel_*} here would duplicate that area's registration once it lands
 *     its own item classes, so those 7 ids are deliberately left out of this file.</li>
 * </ul>
 *
 * <p>CE backs most of the plain-flavor entries here with {@code ItemCustomLore}/
 * {@code ItemBakedBase} (automatic lore-tooltip-from-lang-key lookup, no gameplay effect on any
 * item in this file) or {@code ItemDrop} (drop-triggered effects), all from
 * {@code com.hbm.items.special} - a different concurrent Phase 1 area's package
 * (docs/phase1/items_special.md). As of this writing those two classes are not yet landed there,
 * so the items they would back still register as a plain {@link Item}; swapping the factory lambda
 * to the real special-item class is a one-line change per field once that area lands its base
 * classes, and changes no registry id, hazard binding, or creative-tab placement.
 * {@code com.hbm.items.special.ItemFuel} has since landed, so {@code crystal_coal} below is wired
 * to it directly instead of waiting.
 *
 * <p>{@code plate_armor_titanium}/{@code plate_armor_ajr}/{@code plate_armor_hev}/
 * {@code plate_armor_lunar}/{@code plate_armor_fau}/{@code plate_armor_dnt} are registered in this
 * file. This was cross-checked against the rest of the Phase 1 research wave rather than left as a
 * unilateral call: {@code docs/phase1/DIGEST_REMAINDER.md} (line 73) confirms the entire armor
 * system - {@code ModArmor}, every {@code Armor*}/{@code Jetpack*} class, and by extension anything
 * that consumes these plates as a crafting component - is deferred whole to Phase 3, blocked on
 * NeoForge's {@code Equippable}/data-component armor system. No Phase 1 area (this research wave's
 * 12 reports) claims or registers {@code plate_armor_*}, so there is no live ownership conflict
 * today; these six ids stay here as plain resource items, matching CE's own {@code ItemBase}
 * backing, until the Phase 3 armor area needs them as crafting inputs.</p>
 */
public final class PlateCrystalWasteItems {

    private PlateCrystalWasteItems() {
    }

    /**
     * No-op body - exists purely so {@link ModItems#register} has an explicit call that forces this
     * class to run its static initializers (and therefore register every field below) before
     * {@code ModItems.ITEMS.register(modEventBus)} fires, exactly like {@link MaterialItemGenerator}.
     */
    public static void registerAll() {
    }

    private static DeferredItem<Item> register(String name) {
        return register(name, new Item.Properties());
    }

    private static DeferredItem<Item> register(String name, Item.Properties properties) {
        return ModItems.ITEMS.register(name, () -> new Item(properties));
    }

    private static DeferredItem<Item> registerParts(String name) {
        return registerParts(name, new Item.Properties());
    }

    private static DeferredItem<Item> registerParts(String name, Item.Properties properties) {
        DeferredItem<Item> item = register(name, properties);
        CreativeTabContents.add(ModCreativeTabs.PARTS, item);
        return item;
    }

    // ==================== waste_ (16 CE fields -> 32 flattened variants) ====================
    // CE's ItemDepletedFuel (com.hbm.items.special) is hasSubtypes(true) with exactly 2 metadata
    // variants: 0 = already cooled (lower radiation, no heat) and 1 = freshly generated, still
    // cooling ("Cool in a Spent Fuel Pool Drum" tooltip; HOT hazard applies). Flattened here as
    // <name> (meta 0, cooled/default) and <name>_hot (meta 1) - the "_hot" suffix is a naming
    // decision made for this port, not a CE id, since CE itself only ever had one id per pair.
    // ItemNuclearWaste's custom drop entity (EntityItemWaste, infinite despawn timer) is not ported
    // here - that is an entity-system concern, not an item-registration one; these register as
    // plain Item meanwhile.
    public static final DeferredItem<Item> WASTE_NATURAL_URANIUM = registerParts("waste_natural_uranium");
    public static final DeferredItem<Item> WASTE_NATURAL_URANIUM_HOT = registerParts("waste_natural_uranium_hot");
    public static final DeferredItem<Item> WASTE_URANIUM = registerParts("waste_uranium");
    public static final DeferredItem<Item> WASTE_URANIUM_HOT = registerParts("waste_uranium_hot");
    public static final DeferredItem<Item> WASTE_THORIUM = registerParts("waste_thorium");
    public static final DeferredItem<Item> WASTE_THORIUM_HOT = registerParts("waste_thorium_hot");
    public static final DeferredItem<Item> WASTE_MOX = registerParts("waste_mox");
    public static final DeferredItem<Item> WASTE_MOX_HOT = registerParts("waste_mox_hot");
    public static final DeferredItem<Item> WASTE_PLUTONIUM = registerParts("waste_plutonium");
    public static final DeferredItem<Item> WASTE_PLUTONIUM_HOT = registerParts("waste_plutonium_hot");
    public static final DeferredItem<Item> WASTE_U233 = registerParts("waste_u233");
    public static final DeferredItem<Item> WASTE_U233_HOT = registerParts("waste_u233_hot");
    public static final DeferredItem<Item> WASTE_U235 = registerParts("waste_u235");
    public static final DeferredItem<Item> WASTE_U235_HOT = registerParts("waste_u235_hot");
    public static final DeferredItem<Item> WASTE_SCHRABIDIUM = registerParts("waste_schrabidium");
    public static final DeferredItem<Item> WASTE_SCHRABIDIUM_HOT = registerParts("waste_schrabidium_hot");
    public static final DeferredItem<Item> WASTE_ZFB_MOX = registerParts("waste_zfb_mox");
    public static final DeferredItem<Item> WASTE_ZFB_MOX_HOT = registerParts("waste_zfb_mox_hot");

    // waste_plate_* - 1:1 depleted-fuel companions of the excluded plate_fuel_* items (see class
    // doc). These 7 are still ItemDepletedFuel, not ItemPlateFuel, so they stay in scope here.
    public static final DeferredItem<Item> WASTE_PLATE_U233 = registerParts("waste_plate_u233");
    public static final DeferredItem<Item> WASTE_PLATE_U233_HOT = registerParts("waste_plate_u233_hot");
    public static final DeferredItem<Item> WASTE_PLATE_U235 = registerParts("waste_plate_u235");
    public static final DeferredItem<Item> WASTE_PLATE_U235_HOT = registerParts("waste_plate_u235_hot");
    public static final DeferredItem<Item> WASTE_PLATE_MOX = registerParts("waste_plate_mox");
    public static final DeferredItem<Item> WASTE_PLATE_MOX_HOT = registerParts("waste_plate_mox_hot");
    public static final DeferredItem<Item> WASTE_PLATE_PU239 = registerParts("waste_plate_pu239");
    public static final DeferredItem<Item> WASTE_PLATE_PU239_HOT = registerParts("waste_plate_pu239_hot");
    public static final DeferredItem<Item> WASTE_PLATE_SA326 = registerParts("waste_plate_sa326");
    public static final DeferredItem<Item> WASTE_PLATE_SA326_HOT = registerParts("waste_plate_sa326_hot");
    public static final DeferredItem<Item> WASTE_PLATE_RA226BE = registerParts("waste_plate_ra226be");
    public static final DeferredItem<Item> WASTE_PLATE_RA226BE_HOT = registerParts("waste_plate_ra226be_hot");
    public static final DeferredItem<Item> WASTE_PLATE_PU238BE = registerParts("waste_plate_pu238be");
    public static final DeferredItem<Item> WASTE_PLATE_PU238BE_HOT = registerParts("waste_plate_pu238be_hot");

    // ==================== plate_ (28 fields: plain resources + armor-crafting components) ========
    // Plain metal/composite plates, faithful 1:1 with CE - no hazard bindings exist for this family
    // in CE's HazardRegistry (only plate_fuel_* is radioactive, and that family is excluded above).
    public static final DeferredItem<Item> PLATE_IRON = registerParts("plate_iron");
    public static final DeferredItem<Item> PLATE_COPPER = registerParts("plate_copper");
    public static final DeferredItem<Item> PLATE_TITANIUM = registerParts("plate_titanium");
    public static final DeferredItem<Item> PLATE_ALUMINIUM = registerParts("plate_aluminium");
    public static final DeferredItem<Item> PLATE_GOLD = registerParts("plate_gold");
    public static final DeferredItem<Item> PLATE_LEAD = registerParts("plate_lead");
    public static final DeferredItem<Item> PLATE_STEEL = registerParts("plate_steel");
    public static final DeferredItem<Item> PLATE_COMBINE_STEEL = registerParts("plate_combine_steel");
    public static final DeferredItem<Item> PLATE_PAA = registerParts("plate_paa");
    public static final DeferredItem<Item> PLATE_SATURNITE = registerParts("plate_saturnite");
    public static final DeferredItem<Item> PLATE_SCHRABIDIUM = registerParts("plate_schrabidium");
    public static final DeferredItem<Item> PLATE_DALEKANIUM = registerParts("plate_dalekanium");
    public static final DeferredItem<Item> PLATE_MIXED = registerParts("plate_mixed");
    public static final DeferredItem<Item> PLATE_KEVLAR = registerParts("plate_kevlar");
    public static final DeferredItem<Item> PLATE_POLYMER = registerParts("plate_polymer");
    public static final DeferredItem<Item> PLATE_DESH = registerParts("plate_desh");
    public static final DeferredItem<Item> PLATE_BISMUTH = registerParts("plate_bismuth");
    public static final DeferredItem<Item> PLATE_EUPHEMIUM = registerParts("plate_euphemium");
    public static final DeferredItem<Item> PLATE_DINEUTRONIUM = registerParts("plate_dineutronium");

    // Armor-insert plates: confirmed via docs/phase1/DIGEST_REMAINDER.md:73 that the entire armor
    // system (ModArmor and all Armor*/Jetpack* classes) is deferred whole to Phase 3, and no Phase 1
    // area claims these ids - see class doc. Registered as plain resource items, matching CE.
    public static final DeferredItem<Item> PLATE_ARMOR_TITANIUM = registerParts("plate_armor_titanium");
    public static final DeferredItem<Item> PLATE_ARMOR_AJR = registerParts("plate_armor_ajr");
    public static final DeferredItem<Item> PLATE_ARMOR_HEV = registerParts("plate_armor_hev");
    public static final DeferredItem<Item> PLATE_ARMOR_LUNAR = registerParts("plate_armor_lunar");
    public static final DeferredItem<Item> PLATE_ARMOR_FAU = registerParts("plate_armor_fau");
    public static final DeferredItem<Item> PLATE_ARMOR_DNT = registerParts("plate_armor_dnt");

    public static final DeferredItem<Item> PLATE_DURA_STEEL = registerParts("plate_dura_steel");
    public static final DeferredItem<Item> PLATE_GUNMETAL = registerParts("plate_gunmetal");
    public static final DeferredItem<Item> PLATE_WEAPONSTEEL = registerParts("plate_weaponsteel");

    // ==================== crystal_ / gem_ (38 fields) ==============================================
    // crystal_coal is ItemFuel(name, 6400) in CE (ModItems.java:1806) - wired to the ported
    // com.hbm.items.special.ItemFuel directly rather than registering it as a plain Item.
    private static final int CRYSTAL_COAL_BURN_TIME_TICKS = 6400;
    public static final DeferredItem<Item> CRYSTAL_COAL;

    static {
        DeferredItem<Item> item = ModItems.ITEMS.register("crystal_coal",
                () -> new ItemFuel(new Item.Properties(), CRYSTAL_COAL_BURN_TIME_TICKS));
        CreativeTabContents.add(ModCreativeTabs.PARTS, item);
        CRYSTAL_COAL = item;
    }

    public static final DeferredItem<Item> CRYSTAL_IRON = registerParts("crystal_iron");
    public static final DeferredItem<Item> CRYSTAL_GOLD = registerParts("crystal_gold");
    public static final DeferredItem<Item> CRYSTAL_REDSTONE = registerParts("crystal_redstone");
    public static final DeferredItem<Item> CRYSTAL_LAPIS = registerParts("crystal_lapis");
    public static final DeferredItem<Item> CRYSTAL_DIAMOND = registerParts("crystal_diamond");
    public static final DeferredItem<Item> CRYSTAL_URANIUM = registerParts("crystal_uranium");
    public static final DeferredItem<Item> CRYSTAL_THORIUM = registerParts("crystal_thorium");
    public static final DeferredItem<Item> CRYSTAL_PLUTONIUM = registerParts("crystal_plutonium");
    public static final DeferredItem<Item> CRYSTAL_TITANIUM = registerParts("crystal_titanium");
    public static final DeferredItem<Item> CRYSTAL_SULFUR = registerParts("crystal_sulfur");
    public static final DeferredItem<Item> CRYSTAL_NITER = registerParts("crystal_niter");
    public static final DeferredItem<Item> CRYSTAL_COPPER = registerParts("crystal_copper");
    public static final DeferredItem<Item> CRYSTAL_TUNGSTEN = registerParts("crystal_tungsten");
    public static final DeferredItem<Item> CRYSTAL_ALUMINIUM = registerParts("crystal_aluminium");
    public static final DeferredItem<Item> CRYSTAL_FLUORITE = registerParts("crystal_fluorite");
    public static final DeferredItem<Item> CRYSTAL_BERYLLIUM = registerParts("crystal_beryllium");
    public static final DeferredItem<Item> CRYSTAL_LEAD = registerParts("crystal_lead");
    public static final DeferredItem<Item> CRYSTAL_ASBESTOS = registerParts("crystal_asbestos");
    public static final DeferredItem<Item> CRYSTAL_SCHRARANIUM = registerParts("crystal_schraranium");
    public static final DeferredItem<Item> CRYSTAL_SCHRABIDIUM = registerParts("crystal_schrabidium");
    public static final DeferredItem<Item> CRYSTAL_RARE = registerParts("crystal_rare");
    // Radioactive/hot - see HazardRegistry.registerItems() (CE HazardRegistry.java:502).
    public static final DeferredItem<Item> CRYSTAL_PHOSPHORUS = registerParts("crystal_phosphorus");
    public static final DeferredItem<Item> CRYSTAL_LITHIUM = registerParts("crystal_lithium");
    public static final DeferredItem<Item> CRYSTAL_CINNABAR = registerParts("crystal_cinnabar");
    public static final DeferredItem<Item> CRYSTAL_COBALT = registerParts("crystal_cobalt");
    public static final DeferredItem<Item> CRYSTAL_STARMETAL = registerParts("crystal_starmetal");
    // Radioactive - see HazardRegistry.registerItems() (CE HazardRegistry.java:503).
    public static final DeferredItem<Item> CRYSTAL_TRIXITE = registerParts("crystal_trixite");
    public static final DeferredItem<Item> CRYSTAL_OSMIRIDIUM = registerParts("crystal_osmiridium");

    public static final DeferredItem<Item> GEM_TANTALIUM = registerParts("gem_tantalium");
    public static final DeferredItem<Item> GEM_VOLCANIC =
            registerParts("gem_volcanic", new Item.Properties().rarity(Rarity.UNCOMMON));
    public static final DeferredItem<Item> GEM_SODALITE = registerParts("gem_sodalite");
    // Radioactive - see HazardRegistry.registerItems() (CE HazardRegistry.java:244).
    public static final DeferredItem<Item> GEM_RAD = registerParts("gem_rad");
    // CE's ItemAlexandrite color-shifting logic is left un-ported (CE itself marks it
    // "//TODO: Port ItemAlexandrite for color logic" at ModItems.java:1839) - registers as a plain
    // static-textured item meanwhile.
    public static final DeferredItem<Item> GEM_ALEXANDRITE = registerParts("gem_alexandrite");

    // crystal_xen: CE assigns MainRegistry.controlTab, not partsTab, and caps the stack at 1.
    public static final DeferredItem<Item> CRYSTAL_XEN;

    static {
        DeferredItem<Item> item = register("crystal_xen", new Item.Properties().stacksTo(1));
        CreativeTabContents.add(ModCreativeTabs.CONTROL, item);
        CRYSTAL_XEN = item;
    }

    // crystal_energy: CE sets setCreativeTab(null) - deliberately hidden from every creative tab.
    // Registered but intentionally never passed to CreativeTabContents.add(...).
    public static final DeferredItem<Item> CRYSTAL_ENERGY =
            register("crystal_energy", new Item.Properties().stacksTo(1));

    public static final DeferredItem<Item> CRYSTAL_HORN = registerParts("crystal_horn");
    public static final DeferredItem<Item> CRYSTAL_CHARRED = registerParts("crystal_charred");

    // ==================== fragment_ (9 fields) ======================================================
    // Separate, smaller ore-fragment family from ItemAutogen's FRAGMENT-shape bedrock_ore_fragment
    // (registered by MaterialItemGenerator) - CE treats them as distinct items even where material
    // names overlap (neodymium, cobalt, niobium, boron, lanthanium appear in both families). No
    // hazard bindings exist for this family in CE's HazardRegistry.
    public static final DeferredItem<Item> FRAGMENT_NEODYMIUM = registerParts("fragment_neodymium");
    public static final DeferredItem<Item> FRAGMENT_COBALT = registerParts("fragment_cobalt");
    public static final DeferredItem<Item> FRAGMENT_NIOBIUM = registerParts("fragment_niobium");
    public static final DeferredItem<Item> FRAGMENT_CERIUM = registerParts("fragment_cerium");
    public static final DeferredItem<Item> FRAGMENT_LANTHANIUM = registerParts("fragment_lanthanium");
    public static final DeferredItem<Item> FRAGMENT_ACTINIUM = registerParts("fragment_actinium");
    public static final DeferredItem<Item> FRAGMENT_METEORITE = registerParts("fragment_meteorite");
    public static final DeferredItem<Item> FRAGMENT_BORON = registerParts("fragment_boron");
    public static final DeferredItem<Item> FRAGMENT_COLTAN = registerParts("fragment_coltan");
}
