package com.hbm.datagen;

import com.hbm.blocks.ModBlocks;
import com.hbm.items.ModItems;
import com.hbm.main.MainRegistry;
import net.minecraft.data.PackOutput;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.LanguageProvider;

/**
 * English display names for every registered item/block, plus CE's death-message lang corpus.
 *
 * <p>Item/block names are a simple title-case-from-registry-id fallback (e.g. {@code iron_ingot} ->
 * "Iron Ingot"), generated by iterating {@link ModItems#ITEMS}/{@link ModBlocks#BLOCKS} at datagen
 * time - never a hardcoded id list, so this needs zero coordination with whichever area registers a
 * given item/block. Real, hand-written CE display names are a later polish pass (see this area's
 * final report), not required for Phase 1.
 *
 * <p>Death messages: {@link com.hbm.damage.ModDamageTypes}'s {@code msgId} for each entry is the
 * exact original CE identifier string (see that interface's own javadoc), so every
 * {@code death.attack.<msgId>} key here is CE's own {@code en_us.lang} text carried over unchanged.
 * Only msgIds with a confirmed real CE (or, for the Sedna generic classes, Neo-Edition-reference)
 * source string are ported - {@code enervation}, {@code vacuum} and {@code nitan} have no death
 * message anywhere in either reference and are deliberately left unset rather than invented.
 */
public class ModLanguageProvider extends LanguageProvider {

    public ModLanguageProvider(PackOutput output) {
        super(output, MainRegistry.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        ModItems.ITEMS.getEntries().forEach(holder -> {
            Item item = holder.get();
            this.add(item.getDescriptionId(), titleCase(holder.getId().getPath()));
        });

        ModBlocks.BLOCKS.getEntries().forEach(holder -> {
            Block block = holder.get();
            this.add(block.getDescriptionId(), titleCase(holder.getId().getPath()));
        });

        addDeathMessages();
    }

    private static String titleCase(String registryPath) {
        String[] words = registryPath.split("_");
        StringBuilder result = new StringBuilder(registryPath.length());
        for (String word : words) {
            if (word.isEmpty()) {
                continue;
            }
            if (!result.isEmpty()) {
                result.append(' ');
            }
            result.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
        }
        return result.toString();
    }

    private void addDeathMessages() {
        // CE en_us.lang, ported verbatim for every ModDamageTypes msgId with a real CE source string.
        addDeath("acid", "%1$s fell into acid");
        addDeath("acidPlayer", "%1$s was dissolved by %2$s");
        addDeath("ams", "%1$s was bathed in deadly particles that have yet to be named by human science");
        addDeath("amsCore", "%1$s was vaporized in the fire of a singularity");
        addDeath("asbestos", "%1$s is now entitled to financial compensation");
        addDeath("bang", "%1$s was blasted into bite-sized pieces");
        addDeath("blackhole", "%1$s was spaghettified");
        addDeath("blacklung", "%1$s died from black lung disease");
        addDeath("blast", "%1$s was blown away by an explosion shockwave");
        addDeath("blender", "%1$s was chopped in small, bite-sized pieces");
        addDeath("boat", "%1$s was hit by a boat");
        addDeath("boil", "%1$s was boiled alive by %2$s");
        addDeath("boxcar", "%1$s was smushed by a falling boxcar. Oh well");
        addDeath("broadcast", "%1$s got their brain melted");
        addDeath("building", "%1$s was hit by a falling building");
        addDeath("chopperBullet", "%1$s was rekt by %2$s");
        addDeath("cloud", "%1$s melted like a popsicle in the sun");
        addDeath("cmb", "%1$s was fizzeled by %2$s");
        addDeath("crucible", "%1$s was bisected by a blade of pure Argent energy");
        addDeath("digamma", "%1$s stepped into the abyss");
        addDeath("electricity", "%1$s was electrocuted");
        addDeath("electrified", "%1$s was electrified by %2$s");
        addDeath("euthanized", "%1$s was euthanized by %2$s");
        addDeath("euthanizedSelf", "%1$s euthanized himself, what a dork");
        addDeath("euthanizedSelf2", "%1$s wins the Darwin Award");
        addDeath("exhaust", "%1$s was turned into shish kebab by a starting rocket");
        addDeath("flamethrower", "%1$s was cremated by %2$s");
        addDeath("gunGib", "%1$s was blasted into pieces by %2$s");
        addDeath("ice", "%1$s was turned into a popsicle by %2$s");
        addDeath("laser", "%1$s was turned into ash by %2$s");
        addDeath("lead", "%1$s died from lead poisoning");
        addDeath("lunar", "%1$s forgot to charge their vital organs");
        addDeath("meteorite", "%1$s was hit by a falling rock from outer space");
        addDeath("microwave", "%1$s was exploded by microwave radiation");
        addDeath("mku", "%1$s died from unknown causes");
        addDeath("monoxide", "%1$s forgot to change the batteries in their carbon monoxide detector");
        addDeath("mudPoisoning", "%1$s died in poisonous mud");
        addDeath("nuclearBlast", "%1$s was blown away by a nuclear explosion");
        addDeath("overdose", "%1$s overdosed and asphyxiated");
        addDeath("pc", "%1$s was reduced to a puddle in the pink cloud");
        addDeath("plasma", "%1$s was immolated by %2$s");
        addDeath("radiation", "%1$s died from radiation poisoning");
        addDeath("revolverBullet", "%1$s was shot in the head by %2$s");
        addDeath("rubble", "%1$s was squashed by debris");
        addDeath("shrapnel", "%1$s was ragged by a shrapnel");
        addDeath("slicer", "%1$s was cut in half");
        addDeath("spikes", "%1$s got impaled");
        addDeath("subAtomic1", "%1$s's atoms have been destroyed by %2$s");
        addDeath("subAtomic2", "%1$s was QPU-misaligned because %2$s tampered with their de facto speed");
        addDeath("subAtomic3", "%1$s's divergence dropped below 1 percent because of %2$s");
        addDeath("subAtomic4", "%1$s was divided by zero by %2$s");
        addDeath("subAtomic5", "%1$s was nullified by %2$s");
        addDeath("suicide", "%1$s blew their head off");
        addDeath("taint", "%1$s died from flux tumors");
        addDeath("tau", "%1$s was riddeled by %2$s using negatively charged tauons");
        addDeath("tauBlast", "%1$s charged the XVL1456 for too long and was blown into pieces");

        // Sedna generic damage classes: no CE source (DamageSourceSednaNoAttacker/WithAttacker had no
        // fixed id set), text confirmed from the Neo Edition reference's NtmLanguageProvider.
        addDeath("sednaPhysical", "%1$s was shot");
        addDeathPlayer("sednaPhysical", "%1$s was shot by %2$s");
        addDeath("sednaFire", "%1$s was incinerated");
        addDeathPlayer("sednaFire", "%1$s was incinerated by %2$s");
        addDeath("sednaExplosion", "%1$s was blown up.");
        addDeathPlayer("sednaExplosion", "%1$s was blown up by %2$s.");
        addDeath("sednaElectric", "%1$s was fried");
        addDeathPlayer("sednaElectric", "%1$s was fried by %2$s");
        addDeath("sednaLaser", "%1$s was pulverized");
        addDeathPlayer("sednaLaser", "%1$s was pulverized by %2$s");
        addDeath("sednaMicrowave", "%1$s was microwaved");
        addDeathPlayer("sednaMicrowave", "%1$s was microwaved by %2$s");
        addDeath("sednaSubatomic", "%1$s was atomized");
        addDeathPlayer("sednaSubatomic", "%1$s was atomized by %2$s");
        addDeath("sednaOther", "%1$s was killed");
        addDeathPlayer("sednaOther", "%1$s was killed by %2$s.");
    }

    private void addDeath(String msgId, String message) {
        this.add("death.attack." + msgId, message);
    }

    private void addDeathPlayer(String msgId, String message) {
        this.add("death.attack." + msgId + ".player", message);
    }
}
