package com.hbm.items.machine;

import com.hbm.items.ItemBase;
import com.hbm.util.i18n.I18nUtil;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;

import java.util.List;
import java.util.function.Supplier;

/**
 * RTG (radioisotope thermoelectric generator) pellet. Self-contained half-life/decay math over
 * ItemStack data components; decays into a plain byproduct item ({@code pellet_rtg_depleted_*},
 * one of CE's {@code EnumDepletedRTGMaterial} values, registered alongside this class's instances
 * since it is this item's only reference target) rather than a tile entity.
 */
public class ItemRTGPellet extends ItemBase {

    private static final String[] FACTS = {
            "One gram of Pu-238 costs $8,000.",
            "One gram of Pu-238 produces just under half a Watt of decay heat.",
            "The typical plutonium RTG contains close to eight kilograms of Pu-238.",
            "Pu-238's half life is 87.7 years.",
            "A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
            "Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
            "Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
            "Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
            "Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
            "Thorium reactors are really uranium reactors that convert thorium into U-233.",
            "Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
            "Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
            "Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
            "Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
            "In the 1920s, uranium was considered a useless byproduct of the production of radium.",
            "The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
    };

    private final short heat;
    private final Supplier<? extends Item> decayItem;
    private final long halflife;
    private final long lifespan;

    public ItemRTGPellet(int heat, Supplier<? extends Item> decayItem, long halflife, int halflifes, Properties properties) {
        super(properties.stacksTo(1));
        this.heat = (short) heat;
        this.decayItem = decayItem;
        this.halflife = halflife;
        this.lifespan = halflife * halflifes;
    }

    public long getMaxLifespan() {
        return this.lifespan;
    }

    public long getHalfLife() {
        return this.halflife;
    }

    public short getHeat() {
        return this.heat;
    }

    public ItemStack getDecayItem() {
        return new ItemStack(this.decayItem.get());
    }

    public static long getLifespan(ItemStack stack) {
        if (!(stack.getItem() instanceof ItemRTGPellet pellet)) return 0;
        return stack.getOrDefault(MachineDataComponents.RTG_PELLET_DEPLETION.get(), pellet.lifespan);
    }

    public static void decay(ItemStack stack) {
        if (!(stack.getItem() instanceof ItemRTGPellet)) return;
        stack.set(MachineDataComponents.RTG_PELLET_DEPLETION.get(), getLifespan(stack) - 1);
    }

    public static ItemStack handleDecay(ItemStack stack) {
        if (!(stack.getItem() instanceof ItemRTGPellet pellet)) return stack;
        if (getLifespan(stack) <= 0) return pellet.getDecayItem();
        decay(stack);
        return stack;
    }

    public static double getDecayFraction(ItemStack stack) {
        if (!(stack.getItem() instanceof ItemRTGPellet pellet)) return 0D;
        return Math.pow(0.5, (double) (pellet.lifespan - getLifespan(stack)) / (double) pellet.halflife);
    }

    public static short getScaledPower(ItemStack stack) {
        return stack.getItem() instanceof ItemRTGPellet pellet ? (short) Math.ceil(pellet.heat * getDecayFraction(stack)) : 0;
    }

    @Override
    public InteractionResultHolder<ItemStack> use(Level level, Player player, InteractionHand hand) {
        ItemStack stack = player.getItemInHand(hand);
        if (!level.isClientSide()) {
            player.sendSystemMessage(Component.literal(FACTS[level.getRandom().nextInt(FACTS.length)]).withStyle(ChatFormatting.YELLOW));
        }
        return InteractionResultHolder.success(stack);
    }

    @Override
    public boolean isBarVisible(ItemStack stack) {
        return stack.getItem() instanceof ItemRTGPellet pellet && getLifespan(stack) != pellet.lifespan;
    }

    @Override
    public int getBarWidth(ItemStack stack) {
        return Math.round(13.0F * (1F - (float) getDecayFraction(stack)));
    }

    /** 0 when fresh, 1 when fully depleted — CE {@code getDurabilityForDisplay}. */
    public double getDurabilityForDisplay(ItemStack stack) {
        return 1D - getDecayFraction(stack);
    }

    @Override
    public int getBarColor(ItemStack stack) {
        return 0x40FF40;
    }

    @Override
    public void appendHoverText(ItemStack stack, TooltipContext context, List<Component> tooltip, TooltipFlag flag) {
        if (!(stack.getItem() instanceof ItemRTGPellet pellet)) return;

        tooltip.add(Component.literal(ChatFormatting.RED + I18nUtil.resolveKey("desc.item.rtgHeat", getScaledPower(stack)) + ChatFormatting.RESET));
        tooltip.add(Component.literal(ChatFormatting.GREEN + "Fuel left: " + ((int) (getDecayFraction(stack) * 100000000D)) / 1000000D + "%" + ChatFormatting.RESET));
        tooltip.add(Component.literal(I18nUtil.resolveKey("desc.item.rtgDecay", pellet.getDecayItem().getHoverName().getString())));
        tooltip.add(Component.literal(""));
        tooltip.add(Component.literal(getLifespan(stack) + " / " + pellet.lifespan + " ticks"));

        String[] halfLife = MachineMathUtil.ticksToDate(pellet.halflife);
        String[] timeLeft = MachineMathUtil.ticksToDate(getLifespan(stack));
        String[] maxLife = MachineMathUtil.ticksToDate(pellet.lifespan);
        tooltip.add(Component.literal(String.format("%sHalf life:      %sy %sd %sh %sm %ss%s", ChatFormatting.GREEN, halfLife[0], halfLife[1], halfLife[2], halfLife[3], halfLife[4], ChatFormatting.RESET)));
        tooltip.add(Component.literal(String.format("Time remaining: %sy %sd %sh %sm %ss", timeLeft[0], timeLeft[1], timeLeft[2], timeLeft[3], timeLeft[4])));
        tooltip.add(Component.literal(String.format("Decay Time:     %sy %sd %sh %sm %ss", maxLife[0], maxLife[1], maxLife[2], maxLife[3], maxLife[4])));
    }
}
